openapi: 3.0.0
info:
  title: Fitness API
  version: 1.0.0
  description: |
    This Swagger documentation file outlines the API specifications for a Fitness Tracker application built with Ktor and MongoDB. The API allows users to manage fitness records including creating new records, updating and deleting records by ID. The API uses the Fitness and FitnessDetails data classes to structure the fitness-related information.

paths:
  /fitness:
    post:
      summary: Create a new fitness record
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/FitnessRequest'
      responses:
        '201':
          description: Fitness created successfully
        '400':
          description: Bad request
  /fitness/{id}:
    get:
      summary: Retrieve fitness record by ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              example: {}
        '404':
          description: Fitness not found
    delete:
      summary: Delete fitness record by ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Fitness deleted successfully
        '400':
          description: Bad request
        '404':
          description: Fitness not found
    patch:
      summary: Update fitness record by ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/FitnessRequest'
      responses:
        '200':
          description: Fitness updated successfully
        '400':
          description: Bad request
        '404':
          description: Fitness not found

components:
  schemas:
    Fitness:
      type: object
      properties:
        id:
          type: string
          format: uuid
        exerciseType:
          type: string
        notes:
          type: string
        details:
          $ref: '#/components/schemas/FitnessDetails'
      required:
        - id
        - notes
        - details

    FitnessDetails:
      type: object
      properties:
        durationMinutes:
          type: integer
          format: int32
        distance:
          type: number
          format: double
        caloriesBurned:
          type: integer
          format: int32
      required:
        - durationMinutes
        - distance
        - caloriesBurned

    FitnessRequest:
      type: object
      properties:
        exerciseType:
          type: string
        notes:
          type: string
        details:
          $ref: '#/components/schemas/FitnessDetails'
      required:
        - exerciseType
        - notes
        - details